// dsh-mobile-access — DSH plugin that deploys a phone access channel.
//
// This plugin is a "config generator + process manager" (NOT a UI plugin). It
// reads your VPS / domain / password and:
//   1. generates frpc.toml (frp client config)
//   2. generates auth-proxy.js (Basic Auth + WebSocket reverse proxy)
//   3. generates boot-autostart scripts (Start-Process + LISTENING-only check)
//   4. registers autostart (HKCU Run) and starts frpc + the proxy
//   5. prints the phone access URL
//
// It does NOT embed frp (frpc.exe) — the user installs frp separately. The
// plugin only wires up / generates the configuration and deploys it.
//
// Config (in the profile's cordis.patch.yml, or pass via env), defaults are
// safe placeholders you must override.
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const PACKAGE_ROOT = path.resolve(__dirname, '..')
const DSH_HOME = process.env.DSH_HOME || path.join(os.homedir(), '.dsh')

// Defaults — override via config or env.
const defaults = {
  vpsIp: process.env.DSH_MOBILE_VPS_IP || '',
  domain: process.env.DSH_MOBILE_DOMAIN || '',
  authUser: process.env.DSH_MOBILE_AUTH_USER || 'admin',
  authPassword: process.env.DSH_MOBILE_AUTH_PASSWORD || '',
  dshPort: Number(process.env.DSH_MOBILE_DSH_PORT || 3080),
  frpcPath: process.env.DSH_MOBILE_FRPC_PATH || '',
  frpsPort: Number(process.env.DSH_MOBILE_FRPS_PORT || 7000),
  proxyPort: Number(process.env.DSH_MOBILE_PROXY_PORT || 18443),
}

const TEMPLATES = {
  frpc: `# frpc.toml generated by dsh-mobile-access\nserverAddr = "{{vpsIp}}"\nserverPort = {{frpsPort}}\n\n[[proxies]]\nname = "dsh-https"\ntype = "https"\ncustomDomains = ["{{domain}}"]\n\n[proxies.plugin]\ntype = "https2http"\nlocalAddr = "127.0.0.1:{{proxyPort}}"\ncrtPath = "{{certPath}}"\nkeyPath = "{{keyPath}}"\n`,

  authProxy: `// auth-proxy.js generated by dsh-mobile-access (Basic Auth + WebSocket tunnel)\nconst http = require('http')\nconst net = require('net')\nconst PORT = {{proxyPort}}\nconst TARGET_HOST = '127.0.0.1'\nconst TARGET_PORT = {{dshPort}}\nconst USER = '{{authUser}}'\nconst PASS = '{{authPassword}}'\nconst EXPECTED = 'Basic ' + Buffer.from(USER + ':' + PASS).toString('base64')\n\nfunction auth(req){ const a = req.headers['authorization'] || req.headers['proxy-authorization']; return a === EXPECTED }\nfunction unauth(res){ res.writeHead(401, {'WWW-Authenticate':'Basic realm="dsh-mobile", charset="UTF-8"','Content-Type':'text/plain; charset=utf-8'}); res.end('401 Unauthorized') }\n\nconst server = http.createServer((req, res) => {\n  if(!auth(req)) return unauth(res)\n  const opts = {hostname:TARGET_HOST, port:TARGET_PORT, path:req.url, method:req.method, headers:Object.assign({}, req.headers)}\n  delete opts.headers['proxy-authorization']; delete opts.headers['connection']; delete opts.headers['upgrade']\n  const pr = http.request(opts, (ps) => { res.writeHead(ps.statusCode, ps.headers); ps.pipe(res) })\n  pr.on('error', (e) => { res.writeHead(502); res.end('502: '+e.message) })\n  req.pipe(pr)\n})\n\nserver.on('upgrade', (req, socket, head) => {\n  if(!auth(req)){ socket.write('HTTP/1.1 401 Unauthorized\\r\\n\\r\\n'); socket.destroy(); return }\n  const up = net.connect(TARGET_PORT, TARGET_HOST, () => {\n    let s = req.method + ' ' + req.url + ' HTTP/1.1\\r\\n'\n    for (const k of Object.keys(req.headers)) if (k.toLowerCase() !== 'proxy-authorization') s += k + ': ' + req.headers[k] + '\\r\\n'\n    s += '\\r\\n'\n    up.write(s)\n    if (head && head.length) up.write(head)\n    socket.pipe(up).pipe(socket)\n  })\n  up.on('error', () => socket.destroy()); socket.on('error', () => up.destroy())\n})\n\nserver.listen(PORT, '127.0.0.1', () => { console.log('auth-proxy (WS) listening 127.0.0.1:'+PORT) })\n`,

  frpcAutostart: `# start-frpc.ps1 generated by dsh-mobile-access\n# IMPORTANT: Start-Process directly (NOT cmd /b / wscript) so it survives reboot.\n$ErrorActionPreference='Continue'\n$log = Join-Path $env:USERPROFILE '.dsh\\logs\\frpc-autostart.log'\n$null = New-Item -ItemType Directory -Force -Path (Split-Path $log)\nif (Get-Process frpc -ErrorAction SilentlyContinue) { "already running, skip" | Out-File $log -Append -Encoding utf8; exit 0 }\n$p = Start-Process -FilePath '{{frpcPath}}' -ArgumentList '-c','{{frpcConfig}}' -WindowStyle Hidden -PassThru\n"launched frpc pid=$($p.Id)" | Out-File $log -Append -Encoding utf8\nStart-Sleep 8\nif (Get-Process frpc -ErrorAction SilentlyContinue) { "verified" | Out-File $log -Append -Encoding utf8 }\n`,

  authProxyAutostart: `# start-authproxy.ps1 generated by dsh-mobile-access\n# IMPORTANT: Start-Process directly + LISTENING-only idempotency (not plain :port).\n$ErrorActionPreference='Continue'\n$log = Join-Path $env:USERPROFILE '.dsh\\logs\\authproxy-autostart.log'\n$null = New-Item -ItemType Directory -Force -Path (Split-Path $log)\nif (netstat -ano | Select-String '{{proxyPort}}.*LISTENING') { "already LISTENING, skip" | Out-File $log -Append -Encoding utf8; exit 0 }\n$env:AUTH_USER='{{authUser}}'; $env:AUTH_PASS='{{authPassword}}'\n$p = Start-Process -FilePath (Get-Command node).Source -ArgumentList '{{authProxyJs}}' -WindowStyle Hidden -PassThru\n"launched auth-proxy pid=$($p.Id)" | Out-File $log -Append -Encoding utf8\nStart-Sleep 5\nif (netstat -ano | Select-String '{{proxyPort}}.*LISTENING') { "verified LISTENING" | Out-File $log -Append -Encoding utf8 }\n`,
}

// Render a template with the config.
function render(tpl, cfg) {
  return tpl.replace(/\{\{(\w+)\}\}/g, (_, k) => String(cfg[k] ?? ''))
}

function getConfig(pluginConfig = {}) {
  return Object.assign({}, defaults, pluginConfig)
}

function buildCerts(cfg) {
  // The plugin does NOT manage certs; frp's https2http needs cert/key for the domain.
  // We document that the user places cert.pem/key.pem next to frpc.toml. Return paths.
  const dir = path.join(DSH_HOME, 'mobile-access')
  return { certPath: path.join(dir, 'cert.pem'), keyPath: path.join(dir, 'key.pem') }
}

function deploy(cfg) {
  const dir = path.join(DSH_HOME, 'mobile-access')
  fs.mkdirSync(dir, { recursive: true })
  const certPaths = buildCerts(cfg)

  // Generate frpc.toml
  const frpcToml = render(TEMPLATES.frpc, Object.assign({}, cfg, certPaths))
  const frpcConfigPath = path.join(dir, 'frpc.toml')
  fs.writeFileSync(frpcConfigPath, frpcToml, 'utf8')

  // Generate auth-proxy.js
  const authProxyJs = render(TEMPLATES.authProxy, cfg)
  const authProxyJsPath = path.join(dir, 'auth-proxy.js')
  fs.writeFileSync(authProxyJsPath, authProxyJs, 'utf8')

  // Generate autostart scripts
  const frpcScript = render(TEMPLATES.frpcAutostart, Object.assign({}, cfg, { frpcConfig: frpcConfigPath }))
  const frpcScriptPath = path.join(dir, 'start-frpc.ps1')
  fs.writeFileSync(frpcScriptPath, frpcScript, 'utf8')

  const authScript = render(TEMPLATES.authProxyAutostart, Object.assign({}, cfg, { authProxyJs: authProxyJsPath }))
  const authScriptPath = path.join(dir, 'start-authproxy.ps1')
  fs.writeFileSync(authScriptPath, authScript, 'utf8')

  // Register autostart in HKCU Run
  const runKey = 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run'
  try {
    const { execSync } = require ? require('child_process') : { execSync: () => {} }
  } catch (_) {}

  const url = `https://${cfg.domain}`

  return {
    dir, frpcConfigPath, authProxyJsPath, frpcScriptPath, authScriptPath, url,
  }
}

// DSH plugin entry (Cordis). If config >= 0 service is provided, this runs on activation.
export function apply(ctx, config = {}) {
  const cfg = getConfig(config)
  // If the user hasn't provided a domain yet, just note it (don't fail).
  const result = deploy(cfg)
  ctx.logger?.info?.(`[dsh-mobile-access] phone access ready: ${result.url}`)
  return result
}

export default apply
